#!/bin/sh

# Let script exit when a command fail
set -e

### Check if bash is present in the system
if [ -z "$BASH_VERSION" ]; then
    echo "No version of bash is installed on this system. Exit..."
    exit 0
fi

### Install oh-my-bash
ln -sf $DOTFILES/zsh/.zshrc $HOME/.zshrc
chown -h $(whoami):$(whoami) $HOME/.zshrc

URL="https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh"
if [ ! -d "$HOME/.oh-my-bash" ]; then
    bash -c "$(wget $URL -O -)" "" --unattended
fi

rm .bash_logout .bash_history .bashrc

### Link setting files

# TODO: Check if previous file exists

# System
ln -sf $(pwd)/.profile $HOME/.profile
chown -h $(whoami):$(whoami) $HOME/.profile

# Bash
ln -s $(pwd)/.bash_logout $HOME/.bash_logout #
chown -h $(whoami):$(whoami) $HOME/.bash_logout
ln -s $(pwd)/.bash_profile $HOME/.bash_profile #
chown -h $(whoami):$(whoami) $HOME/.bash_profile
ln -s $(pwd)/.bashrc $HOME/.bashrc #
chown -h $(whoami):$(whoami) $HOME/.bashrc

# Anaconda
ln -s $(pwd)/.condarc $HOME/.condarc #
chown -h $(whoami):$(whoami) $HOME/.condarc

### System
mkdir -p $HOME/bin $HOME/repo $HOME/

### Restart shell
exec bash; source $HOME/.bashrc
